### ISSUE TITLE
YAML parsing issue with b4 release

### ISSUE THREAD

**Issue by ventz** [csirtgadgets/bearded-avenger-deploymentkit#19]
@wesyoung - Following your b4 build for the docker release, and noticed an error in the YAML file.
(clarification - I am pulling the b4 branch, and building the docker release -- but under the standard build I am getting this):

```
Using /tmp/bearded-avenger-deploymentkit/ubuntu16/ansible.cfg as config file
ERROR! Syntax Error while loading YAML.


The error appears to have been in '/tmp/bearded-avenger-deploymentkit/ubuntu16/site.yml': line 47, column 1, but may
be elsewhere in the file depending on the exact syntax problem.

(specified line no longer in file, maybe it changed?)
exception type: <class 'yaml.parser.ParserError'>
exception: while parsing a flow node
expected the node content, but found '<stream end>'
  in "<unicode string>", line 47, column 1:
    
    ^
```

**Comment by wesyoung** [comment]
hrm, got a set of commands i can paste in to re-create this? didn't see this in any of my testing...

**Comment by ventz** [comment]
Ignore -- re-ran it, and it worked. I am not sure what broke in run time, but it was clearly run time related.

**Comment by wesyoung** [comment]
np- i've been trying to nail down those kinds of issues as they come up (i'm about to doc my testing process which is ... quite extensive these days). but doesn't mean we won't miss something.. as we get closer to RC status maybe we can automate some of this so i can more easily see if it's gonna break stuff on your end, etc..

**Comment by wesyoung** [comment]
(err automate some of teh docker checks in travis, along with the stuff i'm doing to test ubuntu, rhel, centos, etc..)..
