### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by shrishtijain** [csirtgadgets/bearded-avenger-deploymentkit#30]
Hi Wes,

I am trying to install cifv3 and facing many issues.
I have attached file having my issues please provide me with solution
![screenshot from 2018-02-12 17-41-24](https://user-images.githubusercontent.com/26400031/36096357-0e5e59b0-101c-11e8-9512-b4f5b8d6a3e7.png)

thanks in advance

**Comment by shrishtijain** [comment]
Hi Wes,

Other issue is as shown below 
Please help me out in solving these queries
![second issue](https://user-images.githubusercontent.com/26400031/36097154-a9cdb6e0-101f-11e8-9f40-792a02ea33df.png)

**Comment by wesyoung** [comment]
hi,

when you open an issue, there's a set of questions that need to be answered- specifically what your logs look like. also- did you try any of the other query combinations in the where do i start page?

https://github.com/csirtgadgets/bearded-avenger-deploymentkit/wiki/Where-do-I-start

usually the system takes an hour or two to do it's initial data load.

re: https://github.com/csirtgadgets/bearded-avenger-deploymentkit/wiki/FAQ#query-failed
