### ISSUE TITLE
Missing Latest Feeds

### ISSUE THREAD

**Issue by shrishtijain** [csirtgadgets/bearded-avenger-deploymentkit#32]
Hello,

Cif server version 3 is installed in my Ubuntu 16 server, but I

 am getting feeds of latest date.
Find attachment below of feeds I had received after running query today, I had highlighted the date in attachment.
[IPLIST06_March.pdf](https://github.com/csirtgadgets/bearded-avenger-deploymentkit/files/1783868/IPLIST06_March.pdf)

Please suggest

**Comment by wesyoung** [comment]
please fill out the issue template with the logging information and re-create the issue.

https://github.com/csirtgadgets/bearded-avenger-deploymentkit/wiki/FAQ
