### ISSUE TITLE
cif v3 hardware requirements

### ISSUE THREAD

**Issue by jpferrero** [csirtgadgets/bearded-avenger-deploymentkit#34]
Hello!

I'm evaluating hardware requirements for CIFv3 and are much lower than CIFv2 xLarge instance. Are these requirements (https://github.com/csirtgadgets/bearded-avenger-deploymentkit/wiki/Hardware) equivalent for a xLage instance? 

Thanks,

**Comment by wesyoung** [comment]
check out:

https://csirtgadgets.com/commits/2018/1/20/deploying-threat-intelligence-platforms-in-10min-or-less

toward the end it shows some of the hardware we've been testing. the resources required for v3 are significantly less than v2, so it's not 1 to 1. if you're un-sure, start with something like 2 cores and 4-8GB of mem and beat the crap out of it for a few weeks. should give you a good idea.
