### ISSUE TITLE
Unsupported parameters for module: daemon_reload

### ISSUE THREAD

**Issue by dylanjacob** [csirtgadgets/bearded-avenger-deploymentkit#38]
# Expected behavior and actual behavior.
Ansible installation should install systemd services and enable them at boot.
During install I get errors when Ansible is enabling services at boot saying:
```
Unsupported parameters for (service) module: dameon_reload Supported parameters include: arguments,enabled,name,pattern,runlevel,sleep,state
```
# Steps to reproduce the problem
In a Dockerfile, I am bringing down bearded-avenger-deploymentkit-3.0.0rc1 and running easybutton.sh. Dockerfile uses ubuntu xenial

# Relevant logs as a result of the actual behavior
```
TASK [csirtgadgets.cif : enable services at boot] ******************************
task path: /opt/bearded-avenger-deploymentkit/roles/csirtgadgets.cif/tasks/router/services.yml:9
failed: [localhost] (item=cif-router.service) => {"changed": false, "failed": true, "item": "cif-router.service", "msg": "Unsupported parameters for (service) module: daemon_reload Supported parameters include: arguments,enabled,name,pattern,runlevel,sleep,state"}
failed: [localhost] (item=cif-httpd.service) => {"changed": false, "failed": true, "item": "cif-httpd.service", "msg": "Unsupported parameters for (service) module: daemon_reload Supported parameters include: arguments,enabled,name,pattern,runlevel,sleep,state"}
```

# Specifications like the version of the project, operating system, or hardware.
Docker ubuntu:xenial, bearded-avenger-deploymentkit 3.0.0rc1

**Comment by wesyoung** [comment]
are you using the same ver of ansible as the deploymentkit:

https://github.com/csirtgadgets/bearded-avenger-deploymentkit/blob/master/ansible.sh

also, there are other docker related issues @ventz is plugging through- i haven't had a chance to look through it yet, maybe the two of you could bounce some ideas around and come up with some PR's ?

in our bootstraps we lock down the minor versions of ansible so we don't run into this as often.. wonder if you ran this with the latest ver of 2.4 if you get teh same thing?

**Comment by wesyoung** [comment]
forgot the issue @ventz posted:

https://github.com/ventz/docker-cif/issues/1#issuecomment-381684140

**Comment by ventz** [comment]
@dylanjacob - I have a working docker version, but when trying to port the latest changes over, I am running into what seems to be a problem around the checking of the distro version.

If you need a functional docker container, this version works perfectly:
https://github.com/ventz/docker-cif

**Comment by dylanjacob** [comment]
@ventz  I'm looking at that now.

**Comment by ventz** [comment]
@wesyoung by the way - I am also using your version of ansible + installed packages/etc.

The only changes really are around the parts that cannot run on docker (firewall, systemd, etc), and that's why we added the the DOCKER flags, so that in the future instead of having to "override" them as they move around, they can just be skipped.

**Comment by dylanjacob** [comment]
@wesyoung I was also using this same approach, however, I was trying to find a way to get the systemd stuff to work, which is where I ran into the error leading to this issue. I was going to try to get all this to work and then use `CMD ['/sbin/init']` in the Dockerfile to see if I could get everything to come up. Still a little new to Docker builds, so that might have been a wild goose chase.

@ventz, if you don't mind, I'd love to work with you towards a successful Docker build on rc1+.

I'll close this issue since it really isn't much of one. Thanks guys :D

**Comment by ventz** [comment]
@dylanjacob Sure - no problem. I think I am really close to getting the latest (and ideally, the final release one) to work with Docker. There's just a couple of tiny things like this.
