### ISSUE TITLE
Upgrade to 3.0.0rc3 fails on Elasticsearch task

### ISSUE THREAD

**Issue by TomStageDK** [csirtgadgets/bearded-avenger-deploymentkit#48]
Hi,

I am trying to upgrade to the latest version.

# Do you have an active https://csirtg.io/support account ? :)
No (Have a free account)
# Expected behavior and actual behavior.
Installation / Upgrade to be successfull, but it fails.
# Steps to reporduce the problem
Try to run the latest bearded-avenger-deploymentkit-3.0.0rc3 on a system that allrdeady have an older version installed
# Relevant logs as a result of the actual behavior
As far as I can find the deploymentkit does not generate any logs
# Specifications like the version of the project, operating system, or hardware.
CIF Version: 3.0.0rc3
OS: Ubuntu 16.04.5 LTS (GNU/Linux 4.4.0-131-generic x86_64)
Kernel: Linux sif 4.4.0-131-generic #157-Ubuntu SMP Thu Jul 12 15:51:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
HW Type:  Virtual (VMWare ESXi)
CPU: 4
RAM: 8GB
Storage: 500G

Error from Installation:
TASK [elastic.elasticsearch : Debian - Ensure elasticsearch is installed] *******************************************************************************************************************************************************************
task path: /root/CIF/bearded-avenger-deploymentkit-3.0.0rc3/roles/elastic.elasticsearch/tasks/elasticsearch-Debian.yml:27
fatal: [localhost]: FAILED! => {"cache_update_time": 1533137956, "cache_updated": false, "changed": false, "msg": "'/usr/bin/apt-get -y -o \"Dpkg::Options::=--force-confdef\" -o \"Dpkg::Options::=--force-confold\"     install 'elasticsearch=5.6.4'' failed: E: Packages were downgraded and -y was used without --allow-downgrades.\n", "rc": 100, "stderr": "E: Packages were downgraded and -y was used without --allow-downgrades.\n", "stderr_lines": ["E: Packages were downgraded and -y was used without --allow-downgrades."], "stdout": "Reading package lists...\nBuilding dependency tree...\nReading state information...\nThe following packages will be DOWNGRADED:\n  elasticsearch\n0 upgraded, 0 newly installed, 1 downgraded, 0 to remove and 0 not upgraded.\n", "stdout_lines": ["Reading package lists...", "Building dependency tree...", "Reading state information...", "The following packages will be DOWNGRADED:", "  elasticsearch", "0 upgraded, 0 newly installed, 1 downgraded, 0 to remove and 0 not upgraded."]}

PLAY RECAP **********************************************************************************************************************************************************************************************************************************
localhost                  : ok=34   changed=1    unreachable=0    failed=1

Elasticsearch Version: 5.6.10

Just let me know if other data is needed.

/Tom

**Comment by cjhc** [comment]
It is trying to downgrade to 5.6.4, which fails (including on a fresh install of CIFv3rc4 if you already have ES installed).

@wesyoung FYI

I got past that on a new test build by purging my ES install, allowing the anisible task to install the old version, apt upgraded it, and the configured it to talk to another node (2 node ES cluster for testing, because I don't listen to advice like "make sure it works with sqlite first" because _you can't live in fear, man_).

I didn't try adding existing indexes back in, but that should (?) work.

**Comment by JesseBowling** [comment]
I'll note that fresh Ubuntu 16 install fail to install with ES on the wait task:

```
TASK [elastic.elasticsearch : Wait for elasticsearch to startup] ***************************************************************************************************************************************************************************************************************
task path: /home/ubuntu/bearded-avenger-deploymentkit/roles/elastic.elasticsearch/tasks/main.yml:52
```
Running deploymentkit install again results in the downgrade error mentioned above. So, the problem is that CIF with ES won't install at all on fresh Ubuntu 16.

Current ES for Ubuntu 16 is 5.6.13 . Currently trying to work through the changes to just try running with that version.

**Comment by JesseBowling** [comment]
*chagrin*

My initial error may actually be lack of resources:

Nov  8 19:10:56 ip-172-31-47-125 elasticsearch[11153]: OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x0000000085330000, 2060255232, 0) failed; error='Cannot allocate memory' (errno=12)
Nov  8 19:10:56 ip-172-31-47-125 elasticsearch[11153]: #
Nov  8 19:10:56 ip-172-31-47-125 elasticsearch[11153]: # There is insufficient memory for the Java Runtime Environment to continue.
Nov  8 19:10:56 ip-172-31-47-125 elasticsearch[11153]: # Native memory allocation (mmap) failed to map 2060255232 bytes for committing reserved memory.
Nov  8 19:10:56 ip-172-31-47-125 elasticsearch[11153]: # An error report file with more information is saved as:
Nov  8 19:10:56 ip-172-31-47-125 elasticsearch[11153]: # /tmp/hs_err_pid11153.log

**Comment by JesseBowling** [comment]
Confirmed that larger machine installs correctly. Also confirmed that at least `cif -p` works with the es_version set to 5.6.13 (but had to change in both global_vars and ubuntu16/site.yml).
