### ISSUE TITLE
easybutton fails on pytest task / pytest 2.8.7 on Ubuntu 16.04.5 LTS

### ISSUE THREAD

**Issue by cjhc** [csirtgadgets/bearded-avenger-deploymentkit#50]
# Do you have an active https://csirtg.io/support account ? :)
No

# Expected behavior and actual behavior.
Expected: build completes.

Actual: build fails on this task
bearded-avenger-deploymentkit-3.0.0rc5/roles/csirtgadgets.cif/tasks/dist.yml:36

pytest==2.8.7 is in Ubuntu 16.04LTS, however the test appears to be looking for pytest>=2.9

# Steps to reproduce the problem
$ sudo CIF_ANSIBLE_ES=localhost:9200 bash easybutton.sh

# Relevant logs as a result of the actual behavior
fatal: [localhost]: FAILED! => {"changed": true, "cmd": ["python", "setup.py", "test"], "delta": "0:00:00.337089", "end": "2018-09-04 13:34:31.070886", "failed": true, "msg": "non-zero return code", "rc": 1, "start": "2018-09-04 13:34:30.733797", "stderr": "Traceback (most recent call last):\n  File \"/usr/bin/py.test\", line 9, in <module>\n    load_entry_point('pytest==2.8.7', 'console_scripts', 'py.test')()\n  File \"/usr/lib/python2.7/dist-packages/_pytest/config.py\", line 38, in main\n    config = _prepareconfig(args, plugins)\n  File \"/usr/lib/python2.7/dist-packages/_pytest/config.py\", line 117, in _prepareconfig\n    pluginmanager=pluginmanager, args=args)\n  File \"/usr/lib/python2.7/dist-packages/_pytest/vendored_packages/pluggy.py\", line 724, in __call__\n    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)\n  File \"/usr/lib/python2.7/dist-packages/_pytest/vendored_packages/pluggy.py\", line 338, in _hookexec\n    return self._inner_hookexec(hook, methods, kwargs)\n  File \"/usr/lib/python2.7/dist-packages/_pytest/vendored_packages/pluggy.py\", line 333, in <lambda>\n    _MultiCall(methods, kwargs, hook.spec_opts).execute()\n  File \"/usr/lib/python2.7/dist-packages/_pytest/vendored_packages/pluggy.py\", line 595, in execute\n    return _wrapped_call(hook_impl.function(*args), self.execute)\n  File \"/usr/lib/python2.7/dist-packages/_pytest/vendored_packages/pluggy.py\", line 249, in _wrapped_call\n    wrap_controller.send(call_outcome)\n  File \"/usr/lib/python2.7/dist-packages/_pytest/helpconfig.py\", line 28, in pytest_cmdline_parse\n    config = outcome.get_result()\n  File \"/usr/lib/python2.7/dist-packages/_pytest/vendored_packages/pluggy.py\", line 279, in get_result\n    _reraise(*ex)  # noqa\n  File \"/usr/lib/python2.7/dist-packages/_pytest/vendored_packages/pluggy.py\", line 264, in __init__\n    self.result = func()\n  File \"/usr/lib/python2.7/dist-packages/_pytest/vendored_packages/pluggy.py\", line 596, in execute\n    res = hook_impl.function(*args)\n  File \"/usr/lib/python2.7/dist-packages/_pytest/config.py\", line 852, in pytest_cmdline_parse\n    self.parse(args)\n  File \"/usr/lib/python2.7/dist-packages/_pytest/config.py\", line 957, in parse\n    self._preparse(args)\n  File \"/usr/lib/python2.7/dist-packages/_pytest/config.py\", line 918, in _preparse\n    self.pluginmanager.load_setuptools_entrypoints(\"pytest11\")\n  File \"/usr/lib/python2.7/dist-packages/_pytest/vendored_packages/pluggy.py\", line 501, in load_setuptools_entrypoints\n    plugin = ep.load()\n  File \"/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py\", line 2324, in load\n    self.require(*args, **kwargs)\n  File \"/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py\", line 2347, in require\n    items = working_set.resolve(reqs, env, installer, extras=self.extras)\n  File \"/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py\", line 786, in resolve\n    raise VersionConflict(dist, req).with_context(dependent_req)\npkg_resources.VersionConflict: (pytest 2.8.7 (/usr/lib/python2.7/dist-packages), Requirement.parse('pytest>=2.9'))\nTraceback (most recent call last):\n  File \"setup.py\", line 29, in <module>\n    raise RuntimeError('tests failed')\nRuntimeError: tests failed", "stderr_lines": ["Traceback (most recent call last):", "  File \"/usr/bin/py.test\", line 9, in <module>", "    load_entry_point('pytest==2.8.7', 'console_scripts', 'py.test')()", "  File \"/usr/lib/python2.7/dist-packages/_pytest/config.py\", line 38, in main", "    config = _prepareconfig(args, plugins)", "  File \"/usr/lib/python2.7/dist-packages/_pytest/config.py\", line 117, in _prepareconfig", "    pluginmanager=pluginmanager, args=args)", "  File \"/usr/lib/python2.7/dist-packages/_pytest/vendored_packages/pluggy.py\", line 724, in __call__", "    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)", "  File \"/usr/lib/python2.7/dist-packages/_pytest/vendored_packages/pluggy.py\", line 338, in _hookexec", "    return self._inner_hookexec(hook, methods, kwargs)", "  File \"/usr/lib/python2.7/dist-packages/_pytest/vendored_packages/pluggy.py\", line 333, in <lambda>", "    _MultiCall(methods, kwargs, hook.spec_opts).execute()", "  File \"/usr/lib/python2.7/dist-packages/_pytest/vendored_packages/pluggy.py\", line 595, in execute", "    return _wrapped_call(hook_impl.function(*args), self.execute)", "  File \"/usr/lib/python2.7/dist-packages/_pytest/vendored_packages/pluggy.py\", line 249, in _wrapped_call", "    wrap_controller.send(call_outcome)", "  File \"/usr/lib/python2.7/dist-packages/_pytest/helpconfig.py\", line 28, in pytest_cmdline_parse", "    config = outcome.get_result()", "  File \"/usr/lib/python2.7/dist-packages/_pytest/vendored_packages/pluggy.py\", line 279, in get_result", "    _reraise(*ex)  # noqa", "  File \"/usr/lib/python2.7/dist-packages/_pytest/vendored_packages/pluggy.py\", line 264, in __init__", "    self.result = func()", "  File \"/usr/lib/python2.7/dist-packages/_pytest/vendored_packages/pluggy.py\", line 596, in execute", "    res = hook_impl.function(*args)", "  File \"/usr/lib/python2.7/dist-packages/_pytest/config.py\", line 852, in pytest_cmdline_parse", "    self.parse(args)", "  File \"/usr/lib/python2.7/dist-packages/_pytest/config.py\", line 957, in parse", "    self._preparse(args)", "  File \"/usr/lib/python2.7/dist-packages/_pytest/config.py\", line 918, in _preparse", "    self.pluginmanager.load_setuptools_entrypoints(\"pytest11\")", "  File \"/usr/lib/python2.7/dist-packages/_pytest/vendored_packages/pluggy.py\", line 501, in load_setuptools_entrypoints", "    plugin = ep.load()", "  File \"/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py\", line 2324, in load", "    self.require(*args, **kwargs)", "  File \"/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py\", line 2347, in require", "    items = working_set.resolve(reqs, env, installer, extras=self.extras)", "  File \"/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py\", line 786, in resolve", "    raise VersionConflict(dist, req).with_context(dependent_req)", "pkg_resources.VersionConflict: (pytest 2.8.7 (/usr/lib/python2.7/dist-packages), Requirement.parse('pytest>=2.9'))", "Traceback (most recent call last):", "  File \"setup.py\", line 29, in <module>", "    raise RuntimeError('tests failed')", "RuntimeError: tests failed"], "stdout": "", "stdout_lines": []}

PLAY RECAP *********************************************************************
localhost                  : ok=67   changed=32   unreachable=0    failed=1  

# Specifications like the version of the project, operating system, or hardware.
3.0.0rc5

**Comment by cjhc** [comment]
After building a new VM with 16.04, a successful easybutton build was possible if updating pytest using pip `sudo pip install -U pytest` to bring it up to 2.9.

**Comment by JesseBowling** [comment]
Similar issue on Ubuntu 18; `sudo apt-get remove python-pytest` followed by `sudo pip install pytest` solves the issue there.

**Comment by coonsmatthew** [comment]
I ran into the same issue, I just ran `sudo pip install --upgrade pytest` and that worked for me.

**Comment by wesyoung** [comment]
can you submit a pull request for this?

https://github.com/csirtgadgets/bearded-avenger-deploymentkit/blob/master/ubuntu16/bootstrap.sh

**Comment by coonsmatthew** [comment]
I'm looking at the bootstrap file, and python-pytest is not called directly, but it must be a dependency of one of the packages called in bootstrap? I did check every package though on the Ubuntu site and don't see python-pytest listed as a dependency of any packages called in boostrap.sh. 

In theory, I could change the script, so apt-get first installs pip, then pip installs pytest, and then apt-get installs the rest of the dependencies. Is that too hacky for you? 

Something like this: 

....
```
echo 'updating packages'
sudo apt-get update && apt-get install python-pip

echo 'installing pytest'
sudo pip install pytest

echo 'installing the basics'
apt-get install -y build-essential python2.7 python-dev aptitude \
    libffi-dev libssl-dev sqlite3 software-properties-common
```
....

**Comment by wesyoung** [comment]
long as it fixes the problem, nothing "too hacky" for me :)

**Comment by sfinlon** [comment]
So this was because of the dev_requirements.txt on bearded-avenger https://github.com/csirtgadgets/bearded-avenger/blob/2ea31582d688b67a5695b14ac476135ba4a0116e/dev_requirements.txt#L3 should we undo the hacky parts and just fix the limits in the requirements file?

**Comment by wesyoung** [comment]
i think if you just test with the latest ver of the libs (pytest vs pycov?) and re-limit the you should be OK.
