### ISSUE TITLE
ran the easybutton

### ISSUE THREAD

**Issue by lmzid** [csirtgadgets/bearded-avenger-deploymentkit#52]
when i ran the easybutton..
[root@T ~/xxxx/bearded-avenger-deploymentkit]# sudo bash easybutton.sh 
Checking for an Internet connection
http://github.com appears to be available via HTTP
------------------
and then, noting happened..
-------------------------------------------------------------------
what did this means?
and I'm using centos7
ask for help!

**Comment by meetzoo** [comment]
If you look over the commands in https://github.com/csirtgadgets/bearded-avenger-deploymentkit/blob/master/easybutton.sh you will see that it probably tries to get the OS and VER from the command 'uname -s' and 'uname -r'. run those commands and see what happens. for me it returned linux and not centos so I just went to the centos7 folder and ran the script manually. it still did not work eventually and I ended up installing on Ubuntu 16.04 on a ec2 machine
