### ISSUE TITLE
cif-router error

### ISSUE THREAD

**Issue by jpferrero** [csirtgadgets/bearded-avenger-deploymentkit#54]
Hello,

I have installed cif-3.0.0rc8 (Ubuntu 16.04) and from time to time suddenly stops inserting data. The process cif-router dies:

cif      15422  0.0  0.0      0     0 ?        Z<   dic14   2:37 [cif-router] <defunct>

It seems that there is a problem inserting 1 indicator and then cif-router process stop working:

dic 21 03:35:57 cif cif-router[15402]: 2018-12-21 03:35:57,170 - DEBUG - cif.store[130][MainThread] - pruning ba158c768ea3b0bfa895f5008e3a99a04a9ee0edf193a6e40cf55b6156bbdb91e9e4ca9288211af8 from create_queue
dic 21 03:38:38 cif cif-router[15402]: 2018-12-21 03:38:38,246 - DEBUG - cif.store[207][MainThread] - flushing queue...
dic 21 03:38:38 cif cif-router[15402]: 2018-12-21 03:38:38,246 - INFO - cif.store[213][MainThread] - attempting to insert 1 indicators..
dic 21 03:38:38 cif cif-router[15402]: Process Process-2:
dic 21 03:38:38 cif cif-router[15402]: Traceback (most recent call last):
dic 21 03:38:38 cif cif-router[15402]:   File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
dic 21 03:38:38 cif cif-router[15402]:     self.run()
dic 21 03:38:38 cif cif-router[15402]:   File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
dic 21 03:38:38 cif cif-router[15402]:     self._target(*self._args, **self._kwargs)
dic 21 03:38:38 cif cif-router[15402]:   File "/usr/local/lib/python2.7/dist-packages/cif-3.0.0rc8-py2.7.egg/cif/store/__init__.py", line 123, in start
dic 21 03:38:38 cif cif-router[15402]:     self._flush_create_queue()
dic 21 03:38:38 cif cif-router[15402]:   File "/usr/local/lib/python2.7/dist-packages/cif-3.0.0rc8-py2.7.egg/cif/store/__init__.py", line 238, in _flush_create_queue
dic 21 03:38:38 cif cif-router[15402]:     n = self.store.indicators.upsert(_t, data)
dic 21 03:38:38 cif cif-router[15402]:   File "/usr/local/lib/python2.7/dist-packages/cif-3.0.0rc8-py2.7.egg/cif/store/zelasticsearch/indicator.py", line 170, in upsert
dic 21 03:38:38 cif cif-router[15402]:     return self.create_bulk(token, indicators, flush=flush)
dic 21 03:38:38 cif cif-router[15402]:   File "/usr/local/lib/python2.7/dist-packages/cif-3.0.0rc8-py2.7.egg/cif/store/zelasticsearch/indicator.py", line 161, in create_bulk
dic 21 03:38:38 cif cif-router[15402]:     helpers.bulk(self.handle, actions, index=self._current_index())
dic 21 03:38:38 cif cif-router[15402]:   File "/usr/local/lib/python2.7/dist-packages/elasticsearch/helpers/__init__.py", line 195, in bulk
dic 21 03:38:38 cif cif-router[15402]:     for ok, item in streaming_bulk(client, actions, **kwargs):
dic 21 03:38:38 cif cif-router[15402]:   File "/usr/local/lib/python2.7/dist-packages/elasticsearch/helpers/__init__.py", line 163, in streaming_bulk
dic 21 03:38:38 cif cif-router[15402]:     for result in _process_bulk_chunk(client, bulk_actions, raise_on_exception, raise_on_error, **kwargs):
dic 21 03:38:38 cif cif-router[15402]:   File "/usr/local/lib/python2.7/dist-packages/elasticsearch/helpers/__init__.py", line 135, in _process_bulk_chunk
dic 21 03:38:38 cif cif-router[15402]:     raise BulkIndexError('%i document(s) failed to index.' % len(errors), errors)
dic 21 03:38:38 cif cif-router[15402]: BulkIndexError: (u'1 document(s) failed to index.', [{u'index': {u'status': 400, u'_type': u'indicator', u'_id': u'AWfOoQSnEZkfAdpk_we3', u'error': {u'caused_by': {u'reason': u"Can't get text on a START_OBJECT at 1:535", u'type': u'illegal_state_exception'}, u'reason': u'failed to parse [additional_data]', u'type': u'mapper_parsing_exception'}, u'_index': u'indicators-2018.12'}}])

In elasticsearch log appears the following error:

[2018-12-21T03:38:38,263][DEBUG][o.e.a.b.TransportShardBulkAction] [localhost-cif] [indicators-2018.12][2] failed to execute bulk item (index) BulkShardRequest [[indicators-2018.12][2]] containing [index {[indicators-2018.12][indicator][AWfOoQSnEZkfAdpk_we3], source[{"count": 1, "indicator": "https://www.acc-appxid-serverno9x82c82ab8.net/?j534j56fsd", "tlp": "green", "group": ["everyone"], "description": "other", "tags": ["phishing"], "altid_tlp": "white", "altid": "http://www.phishtank.com/phish_detail.php?phish_id=5869181", "confidence": 9.0, "protocol": "tcp", "application": ["http", "https"], "reporttime": "2018-12-21T02:38:32.839271Z", "firsttime": "2018-12-07T16:45:35.000000Z", "provider": "phishtank.com", "itype": "url", "lasttime": "2018-12-07T16:45:35.000000Z", "additional_data": [{"detail_time": "2018-12-07T16:50:12+00:00", "country": "US", "rir": "arin", "announcing_network": "15169", "cidr_block": "35.240.0.0/14", "ip_address": "35.243.171.231"}], "uuid": "adf827fe-7be4-44c5-9959-528304ad2fde"}]}]
org.elasticsearch.index.mapper.MapperParsingException: failed to parse [additional_data]

'additional_data' field is mapped as text.

Thanks,

**Comment by sfinlon** [comment]
This should be fixed in release 3.0.1. Code was added https://github.com/csirtgadgets/bearded-avenger/pull/444 to fix it.
