### ISSUE TITLE
Python environment installation error

### ISSUE THREAD

**Issue by lisicn** [csirtgadgets/bearded-avenger-deploymentkit#62]
Thanks for this great project, but I have to ask my questions.

I installed https://github.com/csirtgadgets/threatened-avenger-deploymentkit/wiki according to the instructions

When I execute 'CIF - p', prompt me: 'command' CIF 'not found, did you mean'

This is my 'sudo bash easybutton. sh' execution result
![1](https://user-images.githubusercontent.com/38556416/70223397-a3d62b80-1786-11ea-9aea-5a477b583e81.png)
![2](https://user-images.githubusercontent.com/38556416/70223408-a769b280-1786-11ea-8631-7082d35c2b9f.png)

I try to guess that CIF is generated by installing the request. I even tried the * request file under '/ TMP / boarded-avenger-3.0.7', but all of them returned to me 'error: could not find a version that satisfies the requirement requirements.txt (from versions: none'. I tried to remove the version number, but still the same result. Can you help me, looking forward to your Reply

**Comment by aflick2486** [comment]
I was having the same issue during my installation. I believe the issue has to do with the fact the python 2.7 was being deprecated in January 2020. I was able to solve this by installing the dependencies before running the easybutton.sh. These are the two commands that I run to install all of the dependencies and then run the easybutton again.
- `sudo -H pip install gevent==1.2.1 cifsdk==3.0.8 pygeoip==0.3.2 Flask-Limiter==0.9.5.1 limits==1.1.1 maxminddb==1.3 geoip2==2.8 dnspython==1.15.0 Flask==0.12.3 flask-cors==3.0.8 sqlalchemy==1.0.19 elasticsearch==5.4 elasticsearch-dsl==5.4 html5lib==1.0b8 apwgsdk==0.0.0a6 csirtg_smrt csirtg_dnsdb==0.0.0a4 flask-bootstrap==3.3.6.0 gunicorn==19.7.1 urllib3==1.24.3`
- `sudo -H pip install --ignore-installed pyyaml`

**Comment by zrayburn** [comment]
Are there any plans to migrate CentOS/RHEL to python3?
